odin-flight-booker/config/routes.rb
Rails.application.routes.draw do

	get '/flights' => 'flights#index'

	root 'flights#index'

	resources :bookings, only: [:new, :create, :show]
end

odin-flight-booker/app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departing_flights, :foreign_key => :from, :class_name => "Flight" 
	has_many :arriving_flights, :foreign_key => :to, :class_name => "Flight"
end

odin-flight-booker/app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :flight
	has_many :passengers, :inverse_of => :booking
	accepts_nested_attributes_for :passengers
end

odin-flight-booker/app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :from_airport, :foreign_key => :from, :class_name => "Airport"
	belongs_to :to_airport, :foreign_key => :to, :class_name => "Airport"
	has_many :bookings
	

	def self.possible_dates
		all_dates = Flight.all.map{|flight| flight.departure_time.to_date}.uniq
		all_dates.select{|date| Time.now<=date}
	end

	def self.flight_search(to_id, from_id, date)
		Flight.where(to: to_id).where(from: from_id).where(date: date)
	end

end

odin-flight-booker/app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking, :inverse_of => :passengers
end

odin-flight-booker/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def new
		@flight = Flight.find(params[:flight_id])
		@tickets = params[:tickets]
		@booking = @flight.bookings.build
		build_passengers(params[:tickets], @booking)
	end

	def create
		@booking = Booking.new(booking_params)
		
		if @booking.save
			@booking.passengers.each do |passenger|
				PassengerMailer.welcome_email(passenger).deliver_now
			end
			redirect_to @booking
		else
			@flight = Flight.find(params[:flight_id])
			flash[:danger] = @booking.save!
			render 'new'
		end

	end

	def show
		@booking = Booking.find(params[:id])
	end

	private

	def build_passengers(passengers, booking)
  		if passengers.blank?
  			booking.passengers.build
  		else
  			passengers.to_i.times { @booking.passengers.build }
  		end
  	end

    def booking_params
      	params.require(:booking).permit(:flight_id, 
  		                              :passengers_attributes => [:name, :email])
    end
end

odin-flight-booker/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		@flight_options = Airport.all.map{|u| [u.code, u.id]}
		@passenger_options = [1,2,3,4]
		@date_options = Flight.possible_dates

		@matched_flights = Flight.flight_search(params[:to_id], params[:from_id], params[:date])
	end

	private 

		def flight_params
			params.require(:flight).permit(:from_id, :to_id, :passengers, :date)
		end
end

odin-flight-booker/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

odin-flight-booker/app/helpers/bookings_helper.rb
module BookingsHelper
end

odin-flight-booker/app/helpers/flights_helper.rb
module FlightsHelper
end

odin-flight-booker/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

odin-flight-booker/app/views/bookings/new.html.erb
<h2>Your Booking</h2>
<table>
  <th>Flight number</th>
  <th>Departing</th>
  <th>Arriving</th>
  <th>Date</th>
  <th>Flight Duration</th>
  <th>Passengers</th>
    <tr>
      <td><%= @flight.id%></td>
      <td><%= @flight.from_airport.code %></td>
      <td><%= @flight.to_airport.code %></td>
      <td><%= @flight.date %></td>
      <td><%= @flight.duration %> hours</td>
      <td><%= @tickets %></td>
    </tr>
</table>

<%= form_for(@booking, url: bookings_path) do |f| %>
	<% count = 0 %>
	<%= hidden_field_tag(:flight_id,  params[:flight_id]) %>
    <%= f.hidden_field :flight_id, value: params[:flight_id] %>

	
	<%= f.fields_for(:passengers) do |passenger| %>
		<%= passenger.label :name, "Passenger #{count+=1}" %>
	<%= passenger.text_field :name %>
  <%= passenger.label :email%>
  <%=passenger.text_field :email %>

	<%end%>
	<%= f.submit "Submit booking" %>
<%end%>

odin-flight-booker/app/views/bookings/show.html.erb
<h2>You booked a flight!</h2>

<table>
  <th>Flight number</th>
  <th>Departing</th>
  <th>Arriving</th>
  <th>Date</th>
  <th>Flight Duration</th>
  <%@booking.passengers.count.times do |index| %>
  	<th> Passenger <%=index+1%> </th>
  <%end%>
    <tr>
      <td><%= @booking.flight.id%></td>
      <td><%= @booking.flight.from_airport.code %></td>
      <td><%= @booking.flight.to_airport.code %></td>
      <td><%= @booking.flight.date %></td>
      <td><%= @booking.flight.duration %> hours</td>
      <%@booking.passengers.count.times do |index| %>
      	<td><%=@booking.passengers[index].name%></td>
        <td><%=@booking.passengers[index].email%></td>
      <%end%>
    </tr>
</table>

odin-flight-booker/app/views/flights/index.html.erb
<h1>Flight Booker</h1>

<%= form_for(flights_path, method: :get) do %>
	<%= select_tag(:from_id, options_for_select(@flight_options), prompt: "From") %>
	<%= select_tag(:to_id, options_for_select(@flight_options), prompt: "To") %>
	<%= select_tag(:passengers, options_for_select(@passenger_options),prompt: "Number of Passengers") %>
	<%= select_tag(:date, options_for_select(@date_options), prompt: "Date") %>
	<%= submit_tag("Search Flights") %>

<%end%>

<% if !@matched_flights.empty? %>

<h2>Choose a flight:</h2>

<%= form_tag(new_booking_path, method: :get) do %>
	<%= hidden_field_tag(:tickets, params[:passengers]) %>

	<table>
		<thead>
			<tr>
				<th width = "40"></th>
				<th width = "50">Flight</th>
				<th width = "150">Date</th>
				<th width = "85">Time</th>
				<th width = "50">From</th>
				<th width = "50">To</th>
				<th width = "90">Duration</th>
			</tr>
		</thead>

		<tbody>
			<% @matched_flights.each do |flight| %>
				<tr>
					<td><%= radio_button_tag :flight_id, flight.id %></td>
					<td><%= flight.id %></td>
					<td><%= flight.date%></td>
					<td><%= flight.departure_time.strftime('%H:%M') %> </td>
					<td><%= flight.from_airport.code %></td>
					<td><%= flight.to_airport.code %></td>
					<td><%= flight.duration%> hours</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= submit_tag("Select Flight") %>
<%end%>

<%end%>

odin-flight-booker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

odin-flight-booker/app/views/static_pages/home.html.erb
<h1>Flight Booker</h1>